services:
  postgres:
    image: postgres:15
    container_name: habitstack-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: habitstack-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"